name: CI/CD Pipeline workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main  
  workflow_dispatch:  # Allows manual triggering of the workflow from the GitHub Actions tab    
  schedule:
    - cron: '0 0 * * *'  # Schedules the workflow to run daily at midnight (UTC)        
permissions:
  contents: read  # Grants read permissions for repository contents to the workflow 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository 
       uses: actions/checkout@v3   # Checks out the repository to the runner 
       with:
          fetch-depth: 0   # Fetches the entire history for all branches and tags   

     - name: Mvn Build
       run: mvn clean install   # Builds the project using Maven
       
     - name: Upload Build Artifacts (war)
       uses: actions/upload-artifact@v3  # Uploads build artifacts to be used in subsequent jobs
       with:
         name: build-artifacts  # Name of the artifact
         path: target/*.war  # Path to the generated WAR files from the build

     - name: Notify if the build fails
       if: failure()  # This step will only run if the build fails
       run: echo "Build failed! Please check the logs for details."  # Sends a notification message to the console


  Testing:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Checkout Repository 
       uses: actions/checkout@v3   # Checks out the repository to the runner   
       with:
          fetch-depth: 0   # Fetches the entire history for all branches and tags 

     - name: Mvn Test
       run: mvn test   # Runs the tests using Maven   
      
