name: CI/CD Pipeline code ,y file

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository 
       uses: actions/checkout@v3   # Checks out the repository to the runner 
       with:
          fetch-depth: 0   # Fetches the entire history for all branches and tags   

     - name: Mvn Build
       run: mvn clean install   # Builds the project using Maven
       
  Testing:
    runs-on: ubuntu-latest
    needs: build  
    steps:
     - name: Checkout Repository 
       uses: actions/checkout@v3   # Checks out the repository to the runner   
       with:
          fetch-depth: 0   # Fetches the entire history for all branches and tags 

     - name: Mvn Test
       run: mvn test   # Runs the tests using Maven   
      
